# Generated by Django 2.2.1 on 2019-11-08 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headline',
            old_name='imgae',
            new_name='image',
        ),
    ]
